# Generated by Django 3.0.8 on 2020-07-18 17:24

from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to=job.models.imago)),
                ('Vacancy', models.IntegerField(default=0)),
                ('Salary', models.IntegerField(default=0)),
                ('Job_Nature', models.CharField(choices=[('Full-time', 'Full-time'), ('half time', 'half time')], max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category')),
            ],
        ),
    ]
