# Generated by Django 3.0.8 on 2020-07-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Published_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
